export const enum_state = [
    {
        SUCCESS: 'SUCCESSFUL WORKING',
        FAILED: 'FAILED WORKING',
        INVALID_REQUEST : "FILL ALL REQUEST",
        PENDING: 'WORKING IN PROGRESS',
        DELETE: 'SUCCESSFULLY DELETED',
        UPDATE: 'SUCCESSFULLY UPDATED',
        CREATE: 'SUCCESSFULLY CREATED',
        UPDATE: 'SUCCESSFULLY UPDATED',
        SEARCH: 'SEARCHING',
        ERROR: 'ERROR',
        ALREADY : 'YOU HAVE ALREADY ACCOUNTED',
        LOAN : 'YOUR LOAN APPLICATION IS SUCCESSFUL SUBMITTED',
    }
]